### ISSUE TITLE
InputSystem의 InputActionAsset 객체를 싱글톤 클래스에 넣기

### ISSUE THREAD

**Issue by Ownfos** [Module-Berserk/Module-Berserk#2]
# 현재 상황
1 InputActionAsset을 정의하고 인스펙터의 "generate c# class" 옵션을 활용해 ModuleBerserkActionAssets라는 클래스를 생성
2. PlayerManager와 ItemManager에서 각각 자신만의 ModuleBerserkActionAssets 객체를 private 멤버 변수로 보유
3. 생성한 객체의 InputAction에 callback 함수 추가해서 입력 처리
4. 아이템 습득 UI에서 플레이어의 조작을 잠시 막을 때는 PlayerManager를 참조

# 개선이 필요한 이유
- esc 눌러서 일시정지를 하거나 지금 기획안대로 아이템 습득 UI가 켜지면 게임이 일시정지되는 경우에도 플레이어 조작을 막아야 함
- 또한 위 기능을 담당하는 클래스에서도 자신만의 ModuleBerserkActionAssets를 보유해야 함
- 정리해보면 다음과 같은 상황이 반복될 것으로 보임
1. ModuleBerserkActionAssets 객체를 입력이 필요한 곳마다 생성
=> 어차피 다 같은 InputAction 사용할건데 굳이 중복해서 만들어야 할 이유가 없음
2. 일시정지, 상호작용 UI 시작 등 "플레이어의 입력을 잠시 막고 UI 조작 모드로 전환"이라는 공통적인 기능을 여러 곳에서 구현해야 함
=> 코드 중복, PlayerManager에 대한 종속성 증가

# 개선 방안
### 아이디어
- 지금 상황만 보면 굳이 입력 처리용 객체인 ModuleBerserkActionAssets를 private으로 보유할 필요가 없음
- 또한 ModuleBerserkActionAssets를 생성하고 관리할 책임이 플레이어 캐릭터에게 있다고 생각되지 않음
- 그럼 입력 객체의 생성과 UI 조작 모드 <-> 플레이어 조작 모드를 오고 가는 기능을 담당할 새로운 클래스를 만들면 어떨까?
=> InputManager라는 싱글톤 클래스를 만들어서 아예 입력을 처리하고 싶은 놈들이 모두 InputManager를 사용하도록 변경
=> 메인 화면에서 만들고 DontDestroyOnLoad로 계속 유지하기
=> 나중에 설정 창에서 키 바인딩 변경하는 것 구현하면 그 기능도 이 클래스에 넣으면 깔끔할듯
- 싱글톤 단점이 유닛 테스트가 어렵다는 것인데, 우린 뭐 입력 시스템을 mocking할 일이 없으니까 문제 없다고 생각함
### 상대적 장점
- 입력에 대한 책임을 InputManager 클래스에서 관리하니 책임 소재가 명확함
- 불필요하게 중복되었던 ModuleBerserkActionAssets 객체 생성 및 관리 코드가 한 곳으로 모임
### 상대적 단점
- 입력을 받고 싶으면 항상 InputManager 클래스가 존재해야 함 (empty scene에서 테스트하려는 경우 약간 당황스러울 수 있음)

## 2안
- 아이디어 있으면 제시 바람...

**Comment by VerySadJoy** [comment]
esc같은 Input만 GameManager같은 Script에 달아서 Input을 따로 받으면 안되는지?
ModuleBerserkActionAssets은 말그대로 Player Action만 담당하는 Input을 관리하고 Player와 무관한 Input은 KeyPressed 등으로 단순히 처리해도 상관 없지 않을까여?
